server {
    listen 80;
    listen 8080;
    listen [::]:8080; # <--- Habilita suporte a IPv6 (localhost) 
    server_name localhost;

    # Servir os arquivos do Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Redirecionar requisições /api/ para o container do Backend FastAPI
    location /api/ {
        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
